forge "http://forge.puppetlabs.com"

# Forge modules
mod "jonnyx/resolv_conf"
mod "puppetlabs/concat"
mod "puppetlabs/inifile"
mod "puppetlabs/firewall"
mod "puppetlabs/ntp"
mod "puppetlabs/postgresql"
mod "puppetlabs/puppetdb"
mod "puppetlabs/stdlib"
mod "puppetlabs/vcsrepo"
mod "saz/rsyslog"
mod "stahnma/epel"
mod "thias/sysctl"
